// numstr.cpp -- following number input with line input
// problem:You never get the opportunity to enter the address.
// FIX:add 'cin.get();'after cin >> year
#include <iostream>
int main()
{
	using namespace std;
	cout << "What year was your house built?\n";
	int year;
	cin >> year;//it leaves the newline generated by the Enter key in the input queue
	cin.get();
	cout << "What is its street address?\n";
	char address[80];
	cin.getline(address, 80);//cin.getline() reads the newline as an empty line and assigns a null string to the address array
	cout << "Year built: " << year << endl;
	cout << "Address: " << address << endl;
	cout << "Done!\n";
	return 0;
}
